CREATE TABLE T_COMMENTS (
    ID int(12) NOT NULL AUTO_INCREMENT,
    posts_id int NOT NULL,
    user_id int NOT NULL,
    reply text NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci