CREATE TABLE T_POSTS (
    ID int(12) NOT NULL AUTO_INCREMENT,
    user_id int NOT NULL,
    posts text NOT NULL,
    resolve_flag BOOLEAN NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci